apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-stress-test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: stress-test
  template:
    metadata:
      labels:
        app: stress-test
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: "500m" # Request 0.5 CPU per pod
            memory: "128Mi"
